[package]
name = "rcpp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.5", features = ["derive"] }
lazy-regex = "2.3.0"
subslice_index = "0.5.0"
regex = "1.0.0"
onig = "6"
lazy_static = "1.4.0"
logos = "0.12.1"